[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ah_runpod_sd"
version = "1.0.0"
description = "Text-to-image with Runpod"
requires-python = ">=3.7"
dependencies = ["runpod", "nanoid", "asyncio", "aiohttp"]

